/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbcexam;

//import java.util.Base64;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;
import org.apache.commons.codec.binary.Base64;

/**
 *
 * @author DongHo
 */
public class ADD2 extends javax.swing.JFrame {

     /**
      * Creates new form ADD2
      */
     public ADD2() {
	  initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          txtEmail = new javax.swing.JTextField();
          txtPhoneNumber = new javax.swing.JTextField();
          jButton1 = new javax.swing.JButton();
          jButton2 = new javax.swing.JButton();
          txtPassword = new javax.swing.JPasswordField();
          txtConfirmPassword = new javax.swing.JPasswordField();
          alertWarning = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
          jLabel1.setText("Send Your Contact");

          jLabel2.setText("Email:");

          jLabel3.setText("Password:");

          jLabel4.setText("Confirm Password:");

          jLabel5.setText("Phone number:");

          jButton1.setText("Reset");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          jButton2.setText("Send");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          alertWarning.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
          alertWarning.setForeground(new java.awt.Color(255, 0, 0));
          alertWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addGroup(layout.createSequentialGroup()
                                                  .addGap(24, 24, 24)
                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                       .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jButton2)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jButton1))
                                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                 .addComponent(jLabel2)
                                                                 .addGap(18, 18, 18)
                                                                 .addComponent(txtEmail))
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                             .addGroup(layout.createSequentialGroup()
                                                  .addComponent(jLabel3)
                                                  .addGap(18, 18, 18)
                                                  .addComponent(txtPassword))))
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel5)
                                             .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addComponent(txtConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                             .addComponent(txtPhoneNumber))))
                              .addGap(0, 121, Short.MAX_VALUE))
                         .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(alertWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel2)
                         .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jButton1)
                         .addComponent(jButton2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(alertWarning)
                    .addContainerGap(47, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	  // TODO add your handling code here:
	  if (validateForm()) {
//	       JOptionPane.showMessageDialog(this, "OKE");
	       save();
	  }
     }//GEN-LAST:event_jButton2ActionPerformed

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	  // TODO add your handling code here:
	  resetAll();
     }//GEN-LAST:event_jButton1ActionPerformed

     public void resetAll() {
	  txtEmail.setText("");
	  txtPhoneNumber.setText("");
	  txtPassword.setText("");
	  txtConfirmPassword.setText("");
     }

     public boolean validateForm() {
	  if (txtEmail.getText().trim().equals("")) {
	       alertWarning.setText("Email is not empty");
	       return false;
	  } else {
	       alertWarning.setText("");
	  }
	  if ((txtPassword.getPassword().length > 0) && (txtConfirmPassword.getPassword().length > 0)) {
	       alertWarning.setText("");
	       if (!(new String(txtPassword.getPassword()).equals(new String(txtConfirmPassword.getPassword())))) {
		    alertWarning.setText("Password is not match");
		    return false;
	       } else {
		    alertWarning.setText("");
	       }
	  } else {
	       alertWarning.setText("Password is requied");
	       return false;
	  }
	  if (txtPhoneNumber.getText().trim().equals("")) {
	       alertWarning.setText("Phone number is required");
	       return false;
	  } else {
	       alertWarning.setText("");
	  }
	  return true;
     }
     
     public static String encrypt(String key, String initVector, String password) {
	  try {
	       IvParameterSpec ivp = new IvParameterSpec(initVector.getBytes());

	       SecretKeySpec skey = new SecretKeySpec(key.getBytes(), "AES");

	       Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");

	       cipher.init(Cipher.ENCRYPT_MODE, skey, ivp);

	       byte[] encryptByte = cipher.doFinal(password.getBytes());
	       return Base64.encodeBase64String(encryptByte);
	  } catch (Exception e) {
	       e.printStackTrace();
	       return "";
	  }

     }
     
     public void save() {
	  String email = txtEmail.getText();
	  String password = new String(txtPassword.getPassword());
	  String phone = txtPhoneNumber.getText();
	  password = encrypt("Ngoc123456789653", "Dong123456789653", password);
	  String sqlString = "INSERT INTO Contact (Email, Password, Phone)";
	  sqlString += "VALUES ('" + email + "', '" + password + "', '" + phone + "');";
	  //System.out.println(sqlString);
	  try {
	       getConnection().createStatement().execute(sqlString);
	       resetAll();
	       JOptionPane.showMessageDialog(this, "Success!");
	  } catch (SQLException ex) {
	       System.err.println("Lỗi: " + ex);
	  }
     }

     ////////////// JDBC
     public static Connection getConnection() throws SQLException {
	  String connectionString = "jdbc:mysql://" + "localhost:3306/" + "ContactInfo";
	  return DriverManager.getConnection(connectionString, "root", "");
     }

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
	  /* Set the Nimbus look and feel */
	  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	   */
	  try {
	       for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		    if ("Windows".equals(info.getName())) {
			 javax.swing.UIManager.setLookAndFeel(info.getClassName());
			 break;
		    }
	       }
	  } catch (ClassNotFoundException ex) {
	       java.util.logging.Logger.getLogger(ADD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  } catch (InstantiationException ex) {
	       java.util.logging.Logger.getLogger(ADD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  } catch (IllegalAccessException ex) {
	       java.util.logging.Logger.getLogger(ADD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	       java.util.logging.Logger.getLogger(ADD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  }
	  //</editor-fold>

	  /* Create and display the form */
	  java.awt.EventQueue.invokeLater(new Runnable() {
	       public void run() {
		    new ADD2().setVisible(true);
	       }
	  });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel alertWarning;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JPasswordField txtConfirmPassword;
     private javax.swing.JTextField txtEmail;
     private javax.swing.JPasswordField txtPassword;
     private javax.swing.JTextField txtPhoneNumber;
     // End of variables declaration//GEN-END:variables
}
